---
  - name: VM
    hosts: all
    become: yes
    become_user: root
    collections:
      - ansible.posix
      - community.crypto

    tasks:
      - name: update OS
        yum:
          name: '*'
          state: latest

      - name: reboot from update
        reboot:
          reboot_timeout: 210

      - name: install needed packages
        yum:
          name:
            - postgresql
            - postgresql-server
            - nginx
            - podman
            - dnf-automatic

      - name: enable yum-cron updates
        lineinfile:
          path: /etc/dnf/automatic.conf
          regexp: 'apply_updates = no'
          line: apply_updates = yes

      - name: enable services
        service:
          name: "{{ item }}"
          enabled: yes
          state: started
        with_items:
          - nginx
          - dnf-automatic.timer
          - podman

      - name: Create certifcate directories
        become: true
        file:
          path: /etc/pki/nginx/private
          state: directory
          mode: '755'
      
      - name: Install Python cryptography libs for certificate creation
        become: true
        yum:
          name: python3-cryptography
          state: present
      
      - name: Generate private key
        become: true
        openssl_privatekey:
          path: /etc/pki/nginx/private/server.key
          size: 2048
      
      - name: Generate certificate signing request
        become: true
        openssl_csr:
          path: /etc/ssl/certs/server.crt
          privatekey_path: /etc/pki/nginx/private/server.key
      
      - name: Generate self-signed certificate
        become: true
        x509_certificate:
          path: /etc/pki/nginx/server.crt
          csr_path: /etc/ssl/certs/server.crt
          privatekey_path: /etc/pki/nginx/private/server.key
          provider: selfsigned

      - name: copy Nginx https config
        become: true
        copy:
          src: https.conf
          dest: /etc/nginx/conf.d
      
      - name: Start/Restart Nginx
        become: true
        systemd:
          name: nginx
          state: reloaded
      
      - name: Ensure Firewalld is started
        become: true
        systemd:
          name: firewalld
          state: started
      
      - name: Open firewall port
        become: true
        firewalld:
          port: 443/tcp
          permanent: true
          state: enabled
          immediate: yes

      # setsebool httpd_can_network_connect 1 -P
      - name: Set httpd_can_network_connect flag on and keep it persistent across reboots
        seboolean:
          name: httpd_can_network_connect
          state: yes
          persistent: yes
