- name: misc - install packages
  yum:
    name:
      - cockpit

- name: misc - copy cockpit.conf
  template:
    src: files/cockpit_conf.j2
    dest: /etc/cockpit/cockpit.conf

- name: misc - start cockpit
  systemd:
    name: cockpit
    enabled: yes
    state: reloaded

- name: misc - add user
  user:
    name: trevorcurtis
    groups: wheel
    password: "{{ user_password | password_hash('sha512') }}"

- name: misc - lock down ssh
  lineinfile:
    path: /etc/ssh/sshd_config
    insertafter: '#PasswordAuthentication yes'
    line: 'PasswordAuthentication no'

- name: misc - restart sshd for previous changes
  systemd:
    name: sshd
    enabled: yes
    state: reloaded
