---
- name: docker - setup repo
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: docker - install
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: docker - enable and start
  systemd:
    name: docker
    enabled: yes
    state: restarted
    daemon_reload: yes
