- name: misc - install packages
  yum:
    name:
      - cockpit

- name: misc - copy cockpit.conf
  template:
    src: files/cockpit_conf.j2
    dest: /etc/cockpit/cockpit.conf

- name: misc - start cockpit
  become: true
  systemd:
    name: cockpit
    enabled: yes
    state: reloaded
