- name: misc - install packages
  yum:
    name:
      - cockpit

- name: misc - copy cockpit.conf
  become: true
  copy:
    src: cockpit.conf
    dest: /etc/cockpit/cockpit.conf

- name: misc - start cockpit
  become: true
  systemd:
    name: cockpit
    enabled: yes
    state: reloaded
